server:
  port: 9131
spring:
  application:
    name: alpha-service
  cloud:
    feign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 10000
  profiles:
    active:
    default: development
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  jpa:
    hibernate:
      ddl-auto: none #update to create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true


logging:
  config: classpath:log/log4j2.xml
  level:
    root: INFO
    feign: DEBUG
#    com.alpha: DEBUG